feat(ci): fe8109cd4dcf4aae9d99b1add2103656c41e77ad

diff --git a/.github/workflows/update-sukka-ruleset.yml b/.github/workflows/update-sukka-ruleset.yml
--- a/.github/workflows/update-sukka-ruleset.yml
+++ b/.github/workflows/update-sukka-ruleset.yml
@@ -11,7 +11,7 @@ concurrency:
 
 permissions:
   contents: write
-  # pages: write
+  pages: write
   id-token: write
 
 jobs:
@@ -61,28 +61,50 @@ jobs:
           echo "minute=$(date +'%M')" >> $GITHUB_OUTPUT
           echo "second=$(date +'%S')" >> $GITHUB_OUTPUT
 
+      - name: Download Previous Build
+        uses: actions/checkout@v4
+        with:
+          repository: SukkaLab/ruleset.skk.moe
+          persist-credentials: false
+          path: previous-build-${{ github.run_id }}-${{ github.run_number }}
+          token: ${{ secrets.GIT_TOKEN }}
+
+      - name: Grab building folder
+        id: paths
+        run: |
+          echo "output_dir=previous-build-${{ github.run_id }}-${{ github.run_number }}" >> $GITHUB_OUTPUT
+
+      - name: Setup build folder
+        run: |
+          if [ ! -d ${{ steps.paths.outputs.output_dir }}/.git ]; then
+            echo ".git not found"
+            exit 1
+          fi
+          rm -rf "${{ steps.paths.outputs.output_dir }}/.git"
+
+          if [ ! -d ${{ steps.paths.outputs.output_dir }}/List ]; then
+            mkdir -p "${{ steps.paths.outputs.output_dir }}/List/domainset"
+            touch "${{ steps.paths.outputs.output_dir }}/List/domainset/speedtest.conf"
+          fi
+          echo "public directory is ready: ${{ steps.paths.outputs.output_dir }}"
+
       - name: Restore build process cache
         uses: actions/cache/restore@v4
         id: cache-db-restore
         with:
           path: Sukka Ruleset/upstream/.cache
-          key: ${{ runner.os }}-build-cache-v1-${{ hashFiles('Sukka Ruleset/upstream/pnpm-lock.yaml') }}
+          key: ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }} ${{ steps.date.outputs.hour }}:${{ steps.date.outputs.minute }}:${{ steps.date.outputs.second }}
           restore-keys: |
-            ${{ runner.os }}-build-cache-v1-
+            ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }} ${{ steps.date.outputs.hour }}:${{ steps.date.outputs.minute }}:
+            ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }} ${{ steps.date.outputs.hour }}:
+            ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }}
+            ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-
+            ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-
+            ${{ runner.os }}-v3-
 
       - name: Install dependencies
         run: pnpm install
         working-directory: Sukka Ruleset/upstream
-
-      - name: Define output directory
-        id: paths
-        run: echo "output_dir=./Sukka Ruleset/rulesets" >> $GITHUB_OUTPUT
-
-      - name: Ensure output directory exists and is not empty (specific subdirectories exist and touch files)
-        run: |
-          mkdir -p "${{ steps.paths.outputs.output_dir }}/List/domainset"
-          touch "${{ steps.paths.outputs.output_dir }}/List/domainset/speedtest.conf"
-        shell: bash
 
       - name: Build rulesets
         run: pnpm run build
@@ -107,13 +129,23 @@ jobs:
           fi
           echo "Output directory '$OUTPUT_DIR' exists and is not empty."
 
-      # - name: Fix relative links in generated HTML
-      #   run: |
-      #     OUTPUT_DIR="${{ steps.paths.outputs.output_dir }}"
-      #     echo "Searching for HTML files in $OUTPUT_DIR to fix links..."
-      #     find "$OUTPUT_DIR" -maxdepth 1 -name '*.html' -exec sed -i 's|href="\(List\|Clash\|sing-box\|Modules\|Mock\|Internal\|LegacyClashPremium\|Surfboard\)/|href="./\1/|g' {} +
-      #     echo "Link fixing complete."
-      #   shell: bash
+      - name: Fix relative links in generated HTML
+        run: |
+          OUTPUT_DIR="${{ steps.paths.outputs.output_dir }}"
+          echo "Searching for HTML files in $OUTPUT_DIR to fix links..."
+          find "$OUTPUT_DIR" -maxdepth 1 -name '*.html' -exec sed -i 's|href="\(List\|Clash\|sing-box\|Modules\|Mock\|Internal\|LegacyClashPremium\|Surfboard\)/|href="./\1/|g' {} +
+          echo "Link fixing complete."
+        shell: bash
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: build-artifact-${{ github.sha }}-${{ github.run_number }}
+          path: ${{ steps.paths.outputs.output_dir }}
+          if-no-files-found: error
+          retention-days: 1
+          compression-level: 4
+          include-hidden-files: false
 
       - name: Commit files
         run: |
@@ -147,24 +179,77 @@ jobs:
         uses: actions/cache/save@v4
         with:
           path: Sukka Ruleset/upstream/.cache
-          key: ${{ runner.os }}-build-cache-v1-${{ hashFiles('Sukka Ruleset/upstream/pnpm-lock.yaml') }}
-          lookup-only: true
+          key: ${{ runner.os }}-v3-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }} ${{ steps.date.outputs.hour }}:${{ steps.date.outputs.minute }}:${{ steps.date.outputs.second }}
 
-      # - name: Upload Pages artifact
-      #   uses: actions/upload-pages-artifact@v3
-      #   with:
-      #     path: ${{ steps.paths.outputs.output_dir }}
+      - name: Upload Pages artifact
+        uses: actions/upload-pages-artifact@v3
+        with:
+          path: ${{ steps.paths.outputs.output_dir }}
 
-# deploy_pages:
-#   name: Deploy to GitHub Pages
-#   needs: build_and_commit
-#   runs-on: ubuntu-latest
+  diff_deployment_on_pr:
+    if: github.event_name == 'pull_request'
+    needs:
+      - build_and_commit
+    name: Diff output
+    runs-on: ubuntu-24.04-arm
+    steps:
+      - uses: actions/download-artifact@v4
+        with:
+          name: build-artifact-${{ github.sha }}-${{ github.run_number }}
+          path: public
+      - name: Diff
+        run: |
+          git clone --filter=tree:0 --no-tags https://github.com/SukkaLab/ruleset.skk.moe.git ./deploy-git >/dev/null 2>&1
+          cd ./deploy-git
+          git fetch origin master >/dev/null 2>&1
+          rm -rf ./*
+          cp -rf ../public/* ./
+          git --no-pager diff --minimal
 
-#   environment:
-#     name: github-pages
-#     url: ${{ steps.deployment.outputs.page_url }}
+  deploy_pages:
+    name: Deploy to GitHub Pages
+    needs: build_and_commit
+    runs-on: ubuntu-latest
 
-#   steps:
-#     - name: Deploy to GitHub Pages
-#       id: deployment
-#       uses: actions/deploy-pages@v4
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v4
+
+  # deploy_to_github_dist:
+  #   needs:
+  #     - build_and_commit
+  #   name: Deploy to GitHub Dist
+  #   if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
+  #   runs-on: ubuntu-24.04-arm
+  #   steps:
+  #     - uses: actions/download-artifact@v4
+  #       with:
+  #         name: build-artifact-${{ github.sha }}-${{ github.run_number }}
+  #         path: public
+  #     - name: Upload Dist to GitHub
+  #       continue-on-error: true
+  #       run: |
+  #         gh repo unarchive SukkaLab/ruleset.skk.moe --yes
+  #         git clone --filter=tree:0 --no-tags https://${GH_USER}:${GH_TOKEN}@github.com/SukkaLab/ruleset.skk.moe.git ./deploy-git
+  #         cd ./deploy-git
+  #         git config --global push.default matching
+  #         git config --global user.email "${GH_EMAIL}"
+  #         git config --global user.name "${GH_USER}"
+  #         rm -rf ./*
+  #         cp -rf ../public/* ./
+  #         echo "ruleset.skk.moe" > CNAME
+  #         git add --all .
+  #         git commit -m "deploy: update [${{ steps.date.outputs.cst_time }}]"
+  #         git push --quiet --force origin HEAD:master
+  #         cd ..
+  #         rm -rf ./deploy-git
+  #         gh repo archive SukkaLab/ruleset.skk.moe --yes
+  #       env:
+  #         GH_EMAIL: ${{ secrets.GIT_EMAIL }}
+  #         GH_USER: ${{ secrets.GIT_USER }}
+  #         GH_TOKEN: ${{ secrets.GIT_TOKEN }}
